### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by Mongrul** [mtricht/lunaris#79]
After downloading 0.6 I can't get the program to start. When clicking the batch file the updater window pops up for a few seconds and then vanishes. It appears to make a .lock and .port folder after.   Nothing in my system tray or in task manager. When trying to delete the Lunaris folder windows says its being used, so it must be stuck somewhere.  My java is updated, i double checked.

**Comment by mtricht** [comment]
@Mongrul So you tried redownloading from the zip file and you still can't start?
Can you change the contents of `lunaris.bat` using notepad to:
```
@echo off
cd %~dp0
image\bin\java.exe -jar update4j.jar --remote https://raw.githubusercontent.com/mtricht/lunaris/master/autoupdater.xml --singleInstance
```

What do you see?

Can you also check there's no 'rogue' lunaris running in the background? (Lunaris can only start once)
Check this by opening the task manager and checking if there's any `java.exe` executables open

**Comment by Mongrul** [comment]
Here you go

12:39:38.575 DEBUG dev.tricht.lunaris.com.pathofexile.PathOfExileAPI - Saving explicit mods
12:39:38.576 DEBUG dev.tricht.lunaris.com.pathofexile.PathOfExileAPI - Saving fractured mods
12:39:38.577 DEBUG dev.tricht.lunaris.com.pathofexile.PathOfExileAPI - Saving crafted mods
12:39:38.578 DEBUG dev.tricht.lunaris.com.pathofexile.PathOfExileAPI - Getting leagues from pathofexile.com
Exception in thread "Thread-1" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at org.update4j.service.DefaultLauncher.run(DefaultLauncher.java:119)
        at org.update4j.ConfigImpl.lambda$doLaunch$12(ConfigImpl.java:530)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.update4j.service.DefaultLauncher.run(DefaultLauncher.java:114)
        ... 2 more
Caused by: kotlin.KotlinNullPointerException
        at classpath//dev.tricht.lunaris.util.SystemTray.setup(SystemTray.kt:40)
        at classpath//dev.tricht.lunaris.Lunaris.<init>(Lunaris.kt:71)
        at classpath//dev.tricht.lunaris.Lunaris.<init>(Lunaris.kt:28)
        at classpath//dev.tricht.lunaris.Lunaris$Companion.main(Lunaris.kt:52)
        at classpath//dev.tricht.lunaris.Lunaris.main(Lunaris.kt)
        ... 7 more

**Comment by mtricht** [comment]
@Mongrul Can you try again with v0.6.1?

**Comment by Mongrul** [comment]
Works like a charm! Thank you so much, loving the vulkan fix!
